Feature: Add the ability to configure the SA account lifetime
paralus/paralus pull request #135
Opened 2023-02-02 17:38 UTC by mabhi

Signed-off-by: mabhi <abhijit.mukherjee@infracloud.io>

### What does this PR change?

- Add the ability to configure the SA account lifetime. This also handles persisting new organisation setting for SA de-provision duration, used by relay agent during cleanup of stale resources

### Does the PR depend on any other PRs or Issues? If yes, please list them.

- No

### Checklist

I confirm, that I have...

- [ ] Read and followed the contributing guide in `CONTRIBUTING.md`
- [ ] Added tests for this PR
- [x] Formatted the code using `go fmt` (if applicable)
- [ ] Updated [documentation on the Paralus docs site](https://github.com/paralus/website/blob/main/docs) (if applicable)
- [ ] Updated `CHANGELOG.md`

2023-02-06 11:44 UTC, niravparikh05 requested changes

2023-02-06 11:44 UTC, niravparikh05 commented on api/def/clients/sentry/client/audit_information/audit_information_client.go
> -  AuditInformationLookupCluster audit information lookup cluster API
why do we have these formatting changes ?

2023-02-06 11:44 UTC, niravparikh05 commented on server/kubeconfig.go
> +	ks, err := s.kss.Get(ctx, opts.Organization, sessData.Account, false)
why are we passing account here? this should be organization specific setting and not account specific ..

2023-02-06 11:44 UTC, niravparikh05 commented on server/kubeconfig.go
> +		return &sentryrpc.GetKubeconfigSettingResponse{ValiditySeconds: 31536000, SaValiditySeconds: 28800}, nil
there should be specific validation for mix, max sa validaty seconds..

2023-02-06 11:44 UTC, niravparikh05 commented on server/kubeconfig.go
> +		AccountID:                   opts.Account,
not required, as we are currently in organization context

2023-02-06 11:44 UTC, niravparikh05 commented on internal/models/kubeconfig_setting.go
> +	SaValiditySeconds           int64     `bun:"sa_validity_seconds,notnull,default:0"`
we decided the default will be eight hours right? so it should be the corresponding value in seconds.

2023-02-06 11:44 UTC, niravparikh05 commented on pkg/sentry/authz/authz.go
> +	ks, err := kss.Get(ctx, orgID, accountID, cnAttr.IsSSO)
so, this is an org level setting and not user level

2023-02-07 06:52 UTC, mabhi commented
Cancelling the pull request as opened another one

2023-02-07 06:52 UTC, closed without merging