fix: add custom Empty instead of google.protobuf.Empty
paralus/paralus pull request #291
Opened 2024-02-01 11:59 UTC by rustiever

### What does this PR change?

- as part of https://github.com/paralus/website/pull/105

### Does the PR depend on any other PRs or Issues? If yes, please list them.

-

### Checklist

I confirm, that I have...

- [ ] Read and followed the contributing guide in `CONTRIBUTING.md`
- [ ] Added tests for this PR
- [ ] Formatted the code using `go fmt` (if applicable)
- [ ] Updated [documentation on the Paralus docs site](https://github.com/paralus/website/blob/main/docs) (if applicable)
- [ ] Updated `CHANGELOG.md`

2024-02-01 12:03 UTC, rustiever commented on gen/openapi/proto/rpc/system/idp.swagger.json
> -              "properties": {}
@nirav-rafay @akshay196 
docusaurus plugin was complaining empty `properties` i.e,
`"schema": { "type": "object", "properties": {} }` and it generates an invalid mdx file with no tabs. "schema": {} works as expected though.

2024-02-07 11:01 UTC, niravparikh05 requested changes
@rustiever please find the server impl of idp and oidc which still refers to google protobuf's empty. this will cause build failures as we see few actions are also failing.

2024-02-08 00:32 UTC, rustiever commented
![image](https://github.com/paralus/paralus/assets/60929919/c922812c-e7fb-4392-bdad-58067d64486e)
in paralus there is only these code uses `google.protobuf.Empty`. @niravparikh05 can you pls point me to the code where i need to update?

2024-02-14 11:57 UTC, niravparikh05 approved these changes

2024-02-14 11:58 UTC, merged