Adding testcases for kubeconfig_settings.go
paralus/paralus pull request #46
Opened 2022-07-20 11:12 UTC by vivekhiwarkar

### What does this PR change?

- Added testcases for kubeconfig_settings.go 

### Does the PR depend on any other PRs or Issues? If yes, please list them.

-

### Checklist

I confirm, that I have...

- [X] Read and followed the contributing guide in `CONTRIBUTING.md`
- [ ] Added tests for this PR
- [ ] Formatted the code using `go fmt` (if applicable)
- [ ] Updated [documentation on the Paralus docs site](https://github.com/paralus/website/blob/main/docs) (if applicable)
- [ ] Updated `CHANGELOG.md`

2022-07-21 05:34 UTC, niravparikh05 requested changes

2022-08-01 11:48 UTC, meain commented on pkg/service/kubeconfig_settings_test.go
> +func TestGetKubeconfigSetting(t *testing.T) {
Similar to this, we should also add check for Create and Update.

2022-08-03 04:24 UTC, meain commented on pkg/service/kubeconfig_settings_test.go
> +	mock.ExpectQuery(`SELECT "ks"."id", "ks"."organization_id"`).
@vivekhiwarkar Can we handle the error cases mentioned in the above comment?

2022-08-04 06:18 UTC, meain reviewed
Some small nits, but looks good otherwise.

2022-08-04 06:18 UTC, meain commented on pkg/service/kubeconfig_settings_test.go
> +	kss := &sentry.KubeconfigSetting{Id: uuuid, OrganizationID: ouuid, AccountID: acuuid, ValiditySeconds: int64(validity_seconds), DisableWebKubectl: disable_web_kubectl, DisableCLIKubectl: disable_cli
For a get request, we are fetching based on the ids, and won't have the settings pass on in the request.

2022-08-04 06:18 UTC, meain commented on pkg/service/kubeconfig_settings_test.go
> +		t.Fatal("kubeconfig setting found for invalid user")
It is not `invalid`, but rather `unavailable`.

2022-08-04 06:18 UTC, meain commented on pkg/service/kubeconfig_settings_test.go
> +	mock.ExpectExec(`UPDATE "sentry_kubeconfig_setting" AS "ks" SET .*, validity_seconds = 300, enforce_rsid = FALSE, is_sso_user = FALSE, disable_web_kubectl = TRUE, disable_cli_kubectl = TRUE, enable_
We should probably use the variables you have define up for things like `validity_seconds` and other here instead of hardcoding the values.

2022-08-04 06:18 UTC, meain commented on pkg/service/kubeconfig_settings_test.go
> +			kss := &sentry.KubeconfigSetting{Id: uuuid, OrganizationID: ouuid, AccountID: acuuid, ValiditySeconds: int64(validity_seconds), DisableWebKubectl: disable_web_kubectl, DisableCLIKubectl: disable_c
Get would not need the actual values passed onto the function.

2022-08-04 06:18 UTC, meain commented on pkg/service/kubeconfig_settings_test.go
> +	kss := &sentry.KubeconfigSetting{Id: uuuid, OrganizationID: ouuid, AccountID: acuuid, ValiditySeconds: int64(validity_seconds), DisableWebKubectl: disable_web_kubectl, DisableCLIKubectl: disable_cli
Get would not need the actual values passed onto the function.

2022-08-04 12:27 UTC, meain approved these changes
LGTM

2022-08-05 03:48 UTC, merged